<p class="mainText">Hello!</p>

<p class="mainText">Welcome to BW Shipping, the leading shipping company
on US market. Let me tell you what makes us such a unique company and
why your next shipment must go with us.</p>

<p class="mainText">The main reason it the extremely low prices for
shipments, as well as the stable and reliable service, provided by the
leading world-wide shipping masters such as UPS, FedEx and DHL. We just
started the business in this field, but we already managed to earn the
trust and the gratitude from our clientele.</p>

<p class="mainText">Our low prices are secured due to the high volume
shipping agreements with US major carriers. We use only trustworthy
shipping partners with world-wide famous names and brands. What gives us
the opportunity to offer you such attractive prices is the really high
volume shipment agreements with carriers, and then we just re-sell our
huge quantity of monthly shipments to sole traders and other companies
like yours. <br>
</p>

<p class="mainText">Let me give you an example to illustrate the above.
For instance, we have bought 1000 Second Day Delivery Shipments from
FedEx. Each shipment costs us $18. We're selling it piece by piece to
you for just $22. And this is how it works.</p>
<p class="mainText">You can be assured that in our work we are using
only reputable and well-known carriers which guarantee that your
shipment will be delivered on time.</p>

<p class="mainText">So why look for somewhere else? If shipping is the
important part of your business – you're in the right place.</p>

<p class="mainText">Welcome to BW Shipping – Fast and Reliable!</p>
