<p class="mainText">Here are the answers to our Frequently Asked Questions. Please   read this section before contacting us.</p>
          <p class="mainText"><span class="faq">Q1:</span> <span class="white">Why your prices are so low?</span><br>
<span class="black">A1:</span> Because we're buying   wholesale from the carrier and the re-sell it to the end user. As a wholesale   buyer we are entitled to the huge discounts and that's why we can offer cheap   service for you.<br>
          </p>
          <p class="mainText"><span class="faq">Q2:</span> <span class="white">Can you still be trusted? In my business the fast shipping   is the most important part as I will get a lot of complaints from my customers   if I fail to deliver the goods on time. I would rather pay more to FedEx but   they guarantee my package will be delivered on time.</span><br>
<span class="black">A2:</span> Yes, so do us. We   are using only well-known and trustworthy shipping companies who guarantee the   delivery times. Among our carriers are such reputable companies like FedEx and   UPS.<br>
          </p>
          <p class="mainText"><span class="faq">Q3:</span> <span class="white">I like your prices but not sure about the reliability. Can   I try your service for free?</span><br>
<span class="black">A3:</span> Yes, every new customer can get 3 free   domestic shipments to try. If you like &ndash; you stay with us!
            <BR>
          </p>
          <p class="mainText"><span class="faq">Q4:</span> <span class="white">Do you ship internationally?</span><br>
<span class="black">A4:</span> We don't offer   international shipments yet, but if your company ships a lot abroad, we suggest   you let us know and we will work something out.<br>
          </p>
          <p class="mainText"><span class="faq">Q5:</span><span class="white"> How do I pay for your services?</span><br>
<span class="black">A5:</span> Basically,   everyone pays using his credit card. Our credit cards payments processor is   Google Checkout. However, if you're not comfortable with it, contact us, and we   will find the solution.<br>
          </p>
          <p class="mainText"><span class="faq">Q6:</span> <span class="white">How does the system work? If I want to become your   customer, what should I do?</span><br>
<span class="black">A6:</span> First of all, you have to register with us.   Then, you have to select the best suitable product for you. It depends how often   you ship, how fast you need your shipments to be delivered, how heavy your   shipments are etc. Then, when right product is selected, you pay for it and   receive some fixed quantity of shipments. And you're done &ndash; just go to your   Control Panel and click ADD SHIPMENT - and it is on its way to your   customer.<br>
          </p>
          <p class="mainText"><span class="faq">Q7:</span> <span class="white">How much time does it takes to receive the label?</span><br>
<span class="black">A7:</span> All our orders are processed manually. We're sending the ready shipment every 6   hours, and we are working for you 12 hours a day, from 8 am till 8 pm Eastern   Time. We are working 6 days a week, all weekdays and Saturday. Sunday is day   off. So if you've submitted your shipping request before noon EST then you have   to receive it before 8 pm same day, otherwise you will receive it by 8 am next   working day.<br>
            <br>
            So why look for somewhere else? If shipping is the important   part of your business &ndash; you're in the right place.<br>
          </p>
          <p class="mainText"><span class="faq">Q8:</span><span class="white"> I am registered with you, how do I start shipping?</span><br>
<span class="black">A8:</span> Please log in, select My Shipments, and the click ADD NEW SHIPPMENT. Then enter   receiver's details, item description and desired type of service. Please note   that we are not always able to satisfy your request which carrier should ship   your package, but we always will match the type of service for you. After you   have entered all the details, click SUBMIT and your shipment will appear in your   shipments list as pending. When we have the label for you, you will see the web   link for PDF file, which you have to click and print it. Then you have to   schedule a pick up and stick the printed label on top of the package. The driver   will pick it up from you and you may track the package using our website or   directly form the carrier's website.<br>
          </p>
          <p class="mainText"><span class="faq">Q9:</span> <span class="white">Can you schedule a pick up for me?</span><br>
<span class="black">A9:</span> At the moment we   can't but if the demand for this service will grow, we will introduce this   service as well. Please let us know if you want us to do it for you.<br>
          </p>
          <p class="mainText"><span class="faq">Q10:</span> <span class="white">Can I void the shipment?</span><br>
<span class="black">A10:</span> Yes, you can do so   before you have received the label, or in other words, while your shipment is in   pending status. If you have received your label, and the status of your shipment   has been changed to IN TRANSIT, then it means that the carrier has charged us   for this shipment already, and you're no longer able to void it.<br>
          </p>
          <p class="mainText"><span class="faq">Q11:</span> <span class="white">Can I change the receiver's details? What if I was wrong   or mistaken when submitting the shipment?</span><br>
<span class="black">A11:</span> If your shipment is in pending   status, then you can just void it and submit the new one with correct details in   it. If it is IN TRANSIT status then you can't change it and can't void it, just   don't print the label then. You will still be charged for this shipment, but you   don't have to send it or to give it to pick up driver. And you're always welcome   to submit the new shipment with the correct details in it.<br>
          </p>
          <p class="mainText"><span class="faq">Q12:</span> <span class="white">I have received the label but in SHIPPER field there're   not mine details but the complete strangers. Who are those people and   companies?</span><br>
<span class="black">A12:</span> Those are the details of ours or affiliated with us companies   and people. In order to get high volume discounts from the carrier we need to   show that it will go from different people and locations and therefore we must   have a lot of different affiliated companies and sole traders working with us.   Don't worry about it.<br>
            <br>
            So why look for somewhere else? If shipping is the important   part of your business &ndash; you're in the right place.<br>
          </p>
          <p class="mainText"><span class="faq">Q13:</span> <span class="white">What if I still haven't received the label after 8 am   next working day?</span><br>
<span class="black">A13:</span> Contact us and we will see what was the problem   there.<br>
          </p>
          <p class="mainText"><span class="faq">Q14:</span> <span class="white">How can I see the history of my previous   shipments?</span><br>
<span class="black">A14:</span> Use search field, it will show all your shipments that have   been marked as delivered or that were IN TRANSIT status longer than 7 days.<br>
          </p>
          <p class="mainText"><span class="faq">Q15:</span><span class="white"> Can I get refund for unused shipments?<br>
          </span><span class="black">A15:</span> No,   unfortunately, you can't. But your unused shipments never expire so you can use   them anytime.</p>          
          <p class="mainText"><br>
            <br>
            <span class="smallTextCopyright">&copy; 2009. BW Shipping company.</span><br>
          <img src="img/1px_dummie.gif" alt="" width="1" height="80"></p>
        