
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody>
		<tr>
			<td <? echo'class="tableHeaderCity"'; ?> align="center" valign="top"
				height="210">

			<table class="tableHeaderCity_Trucks" border="0" cellpadding="0" cellspacing="0"
				width="100%">
				<tbody>
					<tr>
						<td align="center" valign="top" width="30%" height="210"><a
							href="#"><img src="img/logo.png" alt="BW Shippping" border="0"
							width="223" height="179"></a></td>
						<td width="70%"></td>
					</tr>
				</tbody>
			</table>

			</td>
		</tr>
	</tbody>
</table>
