<table width="100%"  border="0" cellpadding="0"
	cellspacing="0">
	<tr>
		<td height="210" align="center" valign="top"
			class="tdHeaderPrices">
		<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td width="30%" height="210" align="center" valign="top"><a href="#"><img
					src="img/logo.png" alt="BW Shippping" width="223" height="179"
					border="0"></a></td>
				<td width="70%"></td>
			</tr>
		</table>
		</td>
	</tr>
</table>
