<table background="img/bg_faq_c_under.jpg"
	width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td height="21" align="center" valign="top">
		<table
			class="tableHeadFaqInner"
			width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td " width="30%" height="210" align="center" valign="top"><a
					href="#"><img src="img/logo.png" alt="BW Shippping" width="223"
					height="179" border="0"></a></td>
				<td align="left" valign="top">&nbsp;</td>
			</tr>
		</table>
	</td>
	</tr>
</table>
