<table width="245" height="300" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td align="left" valign="top" class="tdLoginAndCabinetShadow"><table width="231" height="273" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td align="center" valign="middle" class="tdCabinetSignedShape"><table width="231" height="273" border="0" cellspacing="0" cellpadding="0">
                  <tr>

                    <td height="60">&nbsp;</td>
                  </tr>
                  <tr>
                    <td align="center" valign="top"><span class="mainTextWhite"><br>
                    <a href="?pg=myshipments" class= "cabinet">My Shipments</a><br>
                    <a href="?pg=wallet" class="cabinet">My Wallet</a><br>
                   <a href="?pg=profile" class="cabinet">My Profile</a><br>
                    <br>
                     <a href="?pg=oneshipment" class="cabinet">Add Shipment</a></span><br></td>
                 </tr>
                  <tr>
                    <td height="70"><a href="scripts/logout.php" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('button_sign_out','','img/button_sign_out_ol.gif',1)"><img src="img/button_sign_out.gif" alt="sign out" name="button_sign_out" width="231" height="70" border="0"></a></td>
                  </tr>
                </table>
                </td>
              </tr>
              </table>
              <br>

              <a href="?pg=gcheckout"><img src="img/logo_chekout.gif" width="231" height="75" alt="google chekout"></a></td>
          </tr>
          </table>
