<table border="0" cellpadding="1" cellspacing="1" width="800">
	<tbody>
		<tr class="pricesTable_Header">
			<td align="center" bgcolor="#ffffff" valign="middle"><span class="">&nbsp;</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" colspan="2"><span class="">Envelope</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" colspan="2"><span class="">0-2 kg  / 0-5 lb package</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" colspan="2"><span class="">2 - 5 kg / 5 - 12 lb</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" colspan="2"><span class="">5 - 10 kg / 12 - 22 lb</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" colspan="2"><span class="">More than 10 kg / 22 lb</span></td>
		</tr>
		<tr class="pricesTable_Header">
			<td align="left" bgcolor="#ffffff" valign="middle" ><span class="">Type of Service</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" colspan="10"><span class="">&nbsp;</span></td>
		</tr>
		<tr class="pricesTable_Header">
			<td align="center" bgcolor="#ffffff" valign="middle"><span class="">&nbsp;</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Regular Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Our Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Regular Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Our Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Regular Price</span></td>
			<td align="center" bgcolor="#ffffff" valign="middle"><span class="">Our Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Regular Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Our Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Regular Price</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">Our Price</span></td>
		</tr>
		<tr class="pricesTable_Content">
			<td align="center" bgcolor="#ffffff" valign="middle" colspan="11"><span class="">&nbsp;</span></td>
		</tr>
		
		<tr class="pricesTable_Content">
			<td align="center" bgcolor="#ffffff" valign="middle" class="pricesTable_Header"><span class="">GROUND</span></td>
			
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">n/a</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">n/a</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$14,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$10,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$20,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$10,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$31,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$10,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$54,00
</span></td>
<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$15,00
</span></td>
		</tr>
		<tr class="pricesTable_Content">
			<td align="center" bgcolor="#ffffff" valign="middle" class="pricesTable_Header"><span class="">2ND  DAY</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$20,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$10,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$35,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$10,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$60,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$20,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$96,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$40,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$170,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$60,00
</span></td>
		</tr>
		<tr class="pricesTable_Content">
			<td align="center" bgcolor="#ffffff" valign="middle" class="pricesTable_Header"><span class="">NEXT  DAY</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$27,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$10,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$59,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$20,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$100,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$35,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$130,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$50,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$202,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$70,00
</span></td>
		</tr>
		<tr class="pricesTable_Content">
			<td align="center" bgcolor="#ffffff" valign="middle" class="pricesTable_Header"><span class="">PRIORITY EXPRESS</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$60,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$20,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$95,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$35,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$131,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$45,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$166,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$60,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$240,00
</span></td>
			<td align="center" valign="middle" bgcolor="#ffffff" ><span class="">$90,00
</span></td>
		</tr>
	<tr class="pricesTable_Header">
			<td ><p class="mainText"><span class="faq"></span> <span class="white"></span><br></td>
			<td colspan="10"><span class="">&nbsp;</span></td>
		</tr>
		<tr class="pricesTable_Header">
			<td ><p class="mainText"><span class="faq"></span> <span class="pricesTable_ContentWhite">Remarks: 
			</span><br></td>
			<td colspan="10"><span class="">&nbsp;</span></td>
		</tr>
	
		<tr class="pricesTable_Header">
			<td  ><span class=""></span></td>
			<td colspan="10"><span class="">&nbsp;</span></td>
		</tr>
			<tr class="pricesTable_Header">
			<td align="left" colspan="10">
				<p class="mainText">
					<span class="faq"></span>
					<span class="pricesTable_ContentWhite">Prices are given based on www.ups.com website. The shipping route selected was from San Francisco, CA<BR>
zip code 94130 to New York, NY<BR> 
zip code 11218<BR><BR>
If more than 10 kg option selceted the weight given is 44 lbs<BR>
All Regular Prices are estimate<BR>
Maximum weight per single shippment is 158 lbs or 72 kg<BR>
</span></p><br></td>
			<td align="center" ><span class="">&nbsp;</span></td>
		</tr>
		

		</tbody>
</table>
<?php @include("dummy.inc"); ?>