<table>
	<tr>
		<td class="registrationLabel"></td>
		<td class="registrationLabel"></td>
	</tr>
	<tr>
		<td class="registrationLabel"></td>
		<td class="registrationLabel"></td>
	</tr>
	<tr>
		<td colspan="2" class="regiser_left"><?php session_start(); 

		echo 'Thank you! Your password has been sent to '.$_SESSION["login"];

		?></td>
	</tr>
</table>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
